"""init

Revision ID: c12831e25655
Revises:
Create Date: 2025-11-17 21:44:05.593451

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "c12831e25655"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
